### ISSUE TITLE
코드 작동환경..?

### ISSUE THREAD

**Issue by Keunmo** [Taewan-P/attendance-check-nfc#13]
@Taewan-P 
Windows10에서 4410dbd번 커밋 돌렸는데 
ModuleNotFoundError: No module named 'board'
이런 에러가 떴거든..? adafruit pn532 라이브러리 설치한 라즈비안 환경에서만 작동되는거임?

**Comment by Taewan-P** [comment]
ㄴㄴ  pip3 install adafruit-circuitpython-pn532 이거 하셈
아니면 pip 그냥 하던가
