### ISSUE TITLE
개발 방식

### ISSUE THREAD

**Issue by Keunmo** [Taewan-P/attendance-check-nfc#3]
하던대로 기능별로 파일을 따로 만들건지 아니면 내가 했던 todoconsol처럼 한 파일에 다 넣고 함수 단위로 나눌건지 정합시다

**Comment by Taewan-P** [comment]
흠.....이건 어떻게 해야될지 생각을 해봐야 될듯

**Comment by Keunmo** [comment]
기능별로 파일을 따로 만들면 가독성이 더 좋고..음.. 대형 프로젝트들도 다 이렇게 하지 않음? 그런거 연습도 될거같음. 
한 파일안에 넣고 함수단위로 나눠짜면 코딩하긴 더 편해짐. 기능사이에 값 옮기는것도 전역변수로 하면 되고 기능 실행도 함수호출로 간단히 할 수 있음.

**Comment by Taewan-P** [comment]
흠.... 기능별로 파일 만드는거 확실히 좋은데 그 기능별 파일을 객체화시켜야됨

**Comment by Keunmo** [comment]
조만간 함수로 짜져있던거 싹 다 객체로 바꿀거임. 한번엔 안되겠지만.. 조금씩 바꿔서 올릴거임. 근데 그러면 당연히 모든 파일 객체화 작웝 완료될때까지 기능개발이나 테스팅 다 중단될거임. 이거 브랜치를 따로 파서 하는게 좋을듯. 그리고 끝나면 dev에 브랜치 머지하고.

**Comment by Taewan-P** [comment]
ㅇㅇㅇ 근데 그전에 등록 절차랑 출석체크하는거랑 분리 유무를 결정해야되지 않을까 객체화하기전에
우리 아직 새로운 카드 찍고 아무 작업도 안하면 기존카드들 출첵이 안되는 단점이 있음

**Comment by Keunmo** [comment]
그러면 거기에 10초 안에 응답이 없을 시 자동으로 등록 취소되는 기능을 넣어볼께.
