### ISSUE TITLE
ATT db 테이블 변수 이름 바꿉시다

### ISSUE THREAD

**Issue by Keunmo** [Taewan-P/attendance-check-nfc#5]
꼭 바꿔야되는 이유는 딱히 없는데 그냥 기분이 안좋음ㅎㅎ
ATT -> ATD 로 하던가 아니면 아예 ATTENDANCE 로 하는거 어떤지?
ATT로 하니까 자꾸 읽을때 엇ㅅ!!! 으로 읽힘..

**Comment by Taewan-P** [comment]
ㅇㅋ
